#!/usr/bin/env python3

from math import *
from sys import argv

#
def isnum(value):
    try:
        int(value)
        return True
    except ValueError:
        return False

def arithmetic_mean(count, prev_aritmean, value):
    return (count * prev_aritmean + value) / (count + 1)

def standard_deviation(count, prev_sd, value, aritmean, prev_aritmean):
    return sqrt((1 / (count + 1)) * (count *(prev_sd**2 + prev_aritmean**2) + (value**2)) - aritmean**2)

def root_mean_square(aritmean, sd):
    return sqrt(aritmean**2 + sd**2)

def harmonic_mean(count, harmonic, value):
    if (1 / value) == 0 or (count / harmonic) == 0 or (count / harmonic + 1 / value) == 0 or harmonic == 0 or value == 0:
        print("Error. inside of harmonic_mean.")
        exit(84)
    return (count + 1) / (count / harmonic + 1 / value)
#

# Help menu
if len(argv) == 2 and argv[1] == '-h':
    print("USAGE\n\t./104neutrinos n a h sd\n")
    print("DESCRIPTION")
    print("\tn\tnumber of values")
    print("\ta\tarithmetic mean")
    print("\th\tharmonic mean")
    print("\tsd\tstandard deviation")
    exit(0)

# Error handling
if len(argv) != 5:
    print("Error: Invalid amount of argument.")
    exit(84)

for i in range (1, 5):
    if not isnum(argv[i]):
        print("Error: Invalid argument n°", i)
        exit(84)

count = int(argv[1])
aritmean = float(argv[2])
harmonic = float(argv[3])
sd = float(argv[4])

if count < 0:
    print("Error: negative count.")
    exit(84)

# Main loop
while True:
    value = str(input("Enter next value: "))
    prev_aritmean = aritmean
    prev_sd = sd
    if value == "END":
        exit(0)
    elif not isnum(value) or float(value) == 0 or float(harmonic) <= 0 or float(sd) < 0:
          print("Error.")
          exit(84)
    else:
        value = float(value)
        aritmean = arithmetic_mean(count, aritmean, value)
        sd = standard_deviation(count, prev_sd, value, aritmean, prev_aritmean)
        rms = root_mean_square(aritmean, sd)
        harmonic = harmonic_mean(count, harmonic, value)
        count+=1

        print("\tNumber of values:\t", count)
        print("\tStandard deviation:\t", "{:.2f}".format(sd))
        print("\tArithmetic mean:\t", "{:.2f}".format(aritmean))
        print("\tRoot mean square:\t", "{:.2f}".format(rms))
        print("\tHarmonic mean:\t", "{:.2f}".format(harmonic))
        print()
